#####################################################################
# Original author: Việt Anh Bùi | https://github.com/vietanhbui2000 #
#####################################################################

name: Build Padavan Toolchain

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - master
    paths:
      - 'triggers/build-padavan-tlc.md'
#   schedule:
#     - cron: 0 0 * * 1
#   watch:
#     - types: started

env:
  REPO_URL: https://gitlab.com/dm38/padavan-ng
  REPO_BRANCH: master
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH opt/padavan-ng

    - name: Prepare toolchain
      run: |
        cd opt/padavan-ng/toolchain
        ./clean_sources.sh

    - name: Compile toolchain
      run: |
        cd opt/padavan-ng/toolchain
        ./build_toolchain.sh
        echo "::set-env name=DATE::$(date +"%Y%m%d%H%M")"

    - name: Clean up files
      run: |
        cd opt/padavan-ng/toolchain
        tar -cJvf mipsel-linux-uclibc.tar.xz out
        mkdir -p upload
        mv mipsel-linux-uclibc.tar.xz upload

    - name: Upload toolchain directory
      uses: actions/upload-artifact@main
      with:
        name: padavan_toolchain_${{ env.DATE }}
        path: opt/padavan-ng/toolchain/upload
