###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
###############################################################

name: Build OpenWrt Package

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
    paths:
      - 'triggers/build-openwrt-pkg.md'
#   schedule:
#     - cron: 0 0 * * 1
#   watch:
#     - types: started

env:
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Download SDK
      run: |
        mkdir -p openwrt
        cp scripts/openwrt/dl_sdk.sh openwrt/dl_sdk.sh
        cd openwrt
        chmod +x dl_sdk.sh
        ./dl_sdk.sh

    - name: Load package feeds
      run: |
        cd openwrt/sdk
        echo "src-git vietanhbui2000 https://github.com/vietanhbui2000/openwrt-packages.git" >> feeds.conf.default

    - name: Update & install feeds
      run: |
        cd openwrt/sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Generate default configuration
      run: |
        cd openwrt/sdk
        make defconfig

    - name: Compile package
      id: compile
      run: |
        cd openwrt/sdk
        make package/luci-app-argon_theme_settings/compile V=s -j$(nproc)
        make package/luci-app-clear_luci_cache/compile V=s -j$(nproc)
        make package/luci-app-clear_ram/compile V=s -j$(nproc)
        make package/luci-theme-argon/compile V=s -j$(nproc)
        echo "::set-output name=status::success"
        echo "DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Upload package directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success'
      with:
        name: openwrt_package_${{ env.DATE }}
        path: openwrt/sdk/bin/packages
