###########################################################################
# Modifications made by: Việt Anh Bùi | https://github.com/vietanhbui2000 #
###########################################################################

name: Build OpenWrt Package

on:
  release:
    types: published
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-openwrt-pkg.yml'
#  schedule:
#    - cron: 0 0 * * 1
#  watch:
#    - types: started

env:
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo swapoff /swapfile
        sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Download SDK
      run: |
        mkdir -p openwrt

        # wget http://downloads.openwrt.org/releases/19.07.2/targets/ramips/mt7620/openwrt-sdk-19.07.2-ramips-mt7620_gcc-7.5.0_musl.Linux-x86_64.tar.xz
        # tar -xf openwrt-sdk-19.07.2-ramips-mt7620_gcc-7.5.0_musl.Linux-x86_64.tar.xz -C openwrt
        # cd openwrt
        # mv openwrt-sdk-19.07.2-ramips-mt7620_gcc-7.5.0_musl.Linux-x86_64 sdk

        wget https://downloads.openwrt.org/snapshots/targets/ramips/mt7620/openwrt-sdk-ramips-mt7620_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        tar -xf openwrt-sdk-ramips-mt7620_gcc-8.4.0_musl.Linux-x86_64.tar.xz -C openwrt
        cd openwrt
        mv openwrt-sdk-ramips-mt7620_gcc-8.4.0_musl.Linux-x86_64 sdk

    - name: Load package sources
      run: |
        cd openwrt/sdk

        rm feeds.conf.default
        wget https://github.com/coolsnowwolf/lede/raw/master/feeds.conf.default
        echo "src-git vietanhbui2000 https://github.com/vietanhbui2000/openwrt-packages" >> feeds.conf.default

        # echo "src-git Lienol https://github.com/Lienol/openwrt-package" >> feeds.conf.default
        # echo "src-git kenzok8 https://github.com/kenzok8/openwrt-packages" >> feeds.conf.default

    - name: Update & install feeds
      run: |
        cd openwrt/sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: Compile package
      run: |
        cd openwrt/sdk
        make defconfig
        make package/stubby/compile V=s -j$(nproc)

    - name: Upload package
      uses: actions/upload-artifact@v1
      with:
        name: openwrt_package
        path: openwrt/sdk/bin/packages/mipsel_24kc
