###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
#            hanwckf | https://github.com/hanwckf             #
###############################################################

name: Build Asuswrt

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-asuswrt.yml'
#   schedule:
#     - cron: 0 0 * * 1
#   watch:
#     - types: started

env:
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-16.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install libncurses5 libncurses5-dev m4 bison gawk flex libstdc++6-4.4-dev g++-4.4 g++ \
        git gitk zlib1g-dev autoconf autopoint libtool shtool autogen mtd-utils intltool sharutils \
        docbook-xsl-* libstdc++5 texinfo dos2unix xsltproc make pkg-config
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
