###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
#            hanwckf | https://github.com/hanwckf             #
###############################################################

name: Build Padavan

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
    paths:
      - 'triggers/build-padavan-2.md'
#   schedule:
#     - cron: 0 0 * * 1
#   watch:
#     - types: started

env:
  REPO_URL: https://gitlab.com/dm38/padavan-ng
  REPO_BRANCH: master
  DEVICE_NAME: MiWiFi-Mini
  CUSTOMIZE_FIRMWARE: false
  CUSTOMIZE_SH_FILE: scripts/padavan/customize.sh
  USE_PRECOMPILED_TOOLCHAIN: false
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      run: |
        git clone $REPO_URL opt/padavan-ng
        cd opt/padavan-ng
        git checkout $REPO_BRANCH

    - name: Load device configuration
      run: |
        cp -R configs/padavan/$DEVICE_NAME opt/padavan-ng/trunk/configs/boards/XIAOMI
        cp configs/padavan/$DEVICE_NAME.config opt/padavan-ng/trunk/.config
        cp configs/padavan/$DEVICE_NAME.config opt/padavan-ng/trunk/configs/templates/xiaomi/$DEVICE_NAME.config

    - name: Customize firmware
      if: env.CUSTOMIZE_FIRMWARE == 'true' && !cancelled()
      run: |
        cp $CUSTOMIZE_SH_FILE opt/padavan-ng/trunk/customize.sh
        cd opt/padavan-ng/trunk
        chmod +x customize.sh
        ./customize.sh

    - name: Download pre-compiled toolchain
      if: env.USE_PRECOMPILED_TOOLCHAIN == 'true' && !cancelled()
      run: |
        cp scripts/padavan/dl_toolchain.sh opt/padavan-ng/toolchain/dl_toolchain.sh
        cd opt/padavan-ng/toolchain
        sh dl_toolchain.sh

    - name: Compile toolchain
      if: env.USE_PRECOMPILED_TOOLCHAIN == 'false' && !cancelled()
      run: |
        cd opt/padavan-ng/toolchain
        ./clean_sources.sh
        ./build_toolchain.sh

    - name: Clean up files
      run: |
        cd opt/padavan-ng/trunk
        ./clear_tree.sh

    - name: Compile firmware
      id: compile
      run: |
        cd opt/padavan-ng/trunk
        fakeroot ./build_firmware.sh
        echo "::set-output name=status::success"
        echo "DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Upload firmware
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE_NAME }}_padavan_firmware_${{ env.DATE }}
        path: opt/padavan-ng/trunk/images/*.trx
