###########################################################################
# Modifications made by: Việt Anh Bùi | https://github.com/vietanhbui2000 #
# Original author: brvphoenix | https://github.com/brvphoenix             #
###########################################################################

name: Build OpenWrt Package

on:
  release:
    types: published
  push:
    branches:
      - master
    paths:
      - 'triggers/openwrt-package.md'
#  schedule:
#    - cron: 0 0 * * 1
#  watch:
#    - types: started

env:
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build package with Docker
      run: |
        mkdir bin
        svn export https://github.com/brvphoenix/luci-app-wrtbwmon/trunk/luci-app-wrtbwmon
        cp -rf ./luci-app-wrtbwmon ./bin/
        docker pull openwrtorg/sdk:ramips-mt7620-19.07-SNAPSHOT
        docker run --rm --name=test -u root -v "$(pwd)"/bin/:/home/build/openwrt/bin --privileged=true -d openwrtorg/sdk:ramips-mt7620-19.07-SNAPSHOT sleep 1d
        docker exec -i test sed -i 's/git\.openwrt\.org\/project\/luci/github\.com\/openwrt\/luci/g' ./feeds.conf.default
        docker exec -i test ./scripts/feeds update luci
        docker exec -i test ./scripts/feeds install luci
        docker exec -i test mv ./bin/luci-app-wrtbwmon ./package/
        docker exec -i test make defconfig
        docker exec -i test make package/luci-app-wrtbwmon/compile V=s -j$(nproc) | tee >./bin/build.log
        docker stop test

    - name: Prepare files
      run: |
        cd bin && tar -cJf ../build.log.tar.xz build.log && cd ..
        mkdir release
        cp -f ./bin/packages/mipsel_24kc/base/*wrtbwmon* ./release/
        echo "::set-env name=app_path::$(ls ./release/*app-wrtbwmon*)"
        echo "::set-env name=i18n_path::$(ls ./release/*i18n-wrtbwmon*)"

    - name: Upload package
      uses: actions/upload-artifact@v1
      with:
        name: luci-app-wrtbwmon
        path: ${{ env.app_path }}

    - name: Upload i18n package
      uses: actions/upload-artifact@v1
      with:
        name: luci-i18n-wrtbwmon
        path: ${{ env.i18n_path }}

    - name: Upload log file
      uses: actions/upload-artifact@v1
      with:
        name: buildlog
        path: ./build.log.tar.xz
