###########################################################################
# Modifications made by: Việt Anh Bùi | https://github.com/vietanhbui2000 #
###########################################################################

name: Build OpenWrt Package

on:
  release:
    types: published
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-test.yml'
#  schedule:
#    - cron: 0 0 * * 1
#  watch:
#    - types: started

env:
  CONFIG_FILE: configs/lede/MI-MINI.config
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      run: |
        git clone --depth 1 https://github.com/coolsnowwolf/lede -b master lede

    - name: Update & install feeds
      run: |
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load device configuration
      run: |
        [ -e files ] && mv files lede/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE lede/.config

    - name: Generate configuration file
      run: |
        cd lede
        make defconfig

    - name: Download packages
      run: |
        cd lede
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Add additional packages
      run: |
        cd lede/package/lean
        git clone https://github.com/kenzok8/openwrt-packages

    - name: Compile packages
      id: compile
      run: |
        cd lede
        make package/lean/luci-theme-atmaterial/compile V=s -j$(nproc)

    - name: Upload packages
      uses: actions/upload-artifact@v1
      with:
        name: openwrt_package
        path: working/sdk/bin/packages/
