#####################################################################
# Original author: Việt Anh Bùi | https://github.com/vietanhbui2000 #
#####################################################################

name: Build OpenWrt

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - master
    paths:
      - 'triggers/build-openwrt-2.md'
#   schedule:
#     - cron: 0 0 * * 1
#   watch:
#     - types: started

env:
  DEVICE_PROFILE: xiaomi_mir4a-100m
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE_DIR: true
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo apt-get update
        sudo apt-get -y install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python

    - name: Download Image Builder
      run: |
        mkdir -p openwrt
        cp scripts/openwrt/dl_imagebuilder.sh openwrt/dl_imagebuilder.sh
        cd openwrt
        chmod +x dl_imagebuilder.sh
        ./dl_imagebuilder.sh

    - name: Load device script
      run: |
        cp scripts/openwrt/imagebuilder/$DEVICE_PROFILE.sh openwrt/imagebuilder/make.sh

    - name: Compile firmware
      id: compile
      run: |
        cd openwrt/imagebuilder
        chmod +x make.sh
        ./make.sh
        echo "::set-output name=status::success"
        echo "::set-env name=DATE::$(date +"%Y%m%d%H%M")"

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: ${{ env.DEVICE_PROFILE }}_openwrt_bin_${{ env.DATE }}
        path: openwrt/imagebuilder/bin

    - name: Clean up files
      id: cleanup
      if: env.UPLOAD_FIRMWARE_DIR == 'true' && !cancelled()
      run: |
        cd openwrt/imagebuilder/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$PWD"
        echo "::set-output name=status::success"

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.cleanup.outputs.status == 'success' && !cancelled()
      with:
        name: ${{ env.DEVICE_PROFILE }}_openwrt_firmware_${{ env.DATE }}
        path: ${{ env.FIRMWARE }}
