###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
#            P3TERX | https://github.com/P3TERX               #
#            coolsnowwolf | https://github.com/coolsnowwolf   #
###############################################################

name: Build OpenWrt

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
    paths:
      - 'triggers/build-openwrt.md'
#   schedule:
#     - cron: 0 0 * * 1
#   watch:
#     - types: started

env:
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
  REPO_BRANCH: openwrt-18.06
  DEVICE_CONFIG_FILE: configs/openwrt/xiaomi_miwifi-mini.config
  CUSTOMIZE_FIRMWARE: false
  CUSTOMIZE_SH_FILE: scripts/openwrt/customize.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE_DIR: true
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      run: |
        git clone $REPO_URL openwrt
        cd openwrt
        git checkout $REPO_BRANCH

    - name: Update & install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load device configuration
      run: |
        cp $DEVICE_CONFIG_FILE openwrt/.config

    - name: Customize firmware
      if: env.CUSTOMIZE_FIRMWARE == 'true' && !cancelled()
      run: |
        cp $CUSTOMIZE_SH_FILE openwrt/customize.sh
        cd openwrt
        chmod +x customize.sh
        ./customize.sh

    - name: Generate default configuration
      run: |
        cd openwrt
        make defconfig

    - name: Download packages
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "::set-output name=status::success"
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: ${{ env.DEVICE_NAME }}_openwrt_bin_${{ env.DATE }}
        path: openwrt/bin

    - name: Clean up files
      id: cleanup
      if: env.UPLOAD_FIRMWARE_DIR == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.cleanup.outputs.status == 'success' && !cancelled()
      with:
        name: ${{ env.DEVICE_NAME }}_openwrt_firmware_${{ env.DATE }}
        path: ${{ env.FIRMWARE }}
