###########################################################################
# Modifications made by: Việt Anh Bùi | https://github.com/vietanhbui2000 #
# Original author: chongshengB | https://github.com/chongshengB           #
###########################################################################
#

name: Build Padavan

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-padavan-2.yml'
#  schedule:
#    - cron: 0 0 * * 1
#  watch:
#    - types: started

env:
  REPO_URL: https://github.com/vietanhbui2000/padavan-ng
  REPO_BRANCH: master
  DEVICE_NAME: MiWiFi-4A
  CUSTOMIZE_FIRMWARE: false
  CUSTOMIZE_SH_FILE: scripts/padavan/customize.sh
  USE_PRECOMPILED_TOOLCHAIN: true
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget \
        module-init-tools

    - name: Clone source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH opt/padavan-ng

    - name: Load device configuration
      run: |
        cp -R configs/padavan/$DEVICE_NAME opt/padavan-ng/trunk/configs/boards/XIAOMI
        cp configs/padavan/$DEVICE_NAME.config opt/padavan-ng/trunk/.config
        cp configs/padavan/$DEVICE_NAME.config opt/padavan-ng/trunk/configs/templates/xiaomi/$DEVICE_NAME.config

    - name: Customize firmware
      if: env.CUSTOMIZE_FIRMWARE == 'true' && !cancelled()
      run: |
        cp $CUSTOMIZE_SH_FILE opt/padavan-ng/trunk/customize.sh
        cd opt/padavan-ng/trunk
        chmod +x customize.sh
        ./customize.sh

    - name: Prepare toolchain
      run: |
        cd opt/padavan-ng/toolchain
        ./clean_sources.sh

    - name: Download pre-compiled toolchain
      if: env.USE_PRECOMPILED_TOOLCHAIN == 'true' && !cancelled()
      run: |
        cp scripts/padavan/dl_toolchain.sh opt/padavan-ng/toolchain/dl_toolchain.sh
        cd opt/padavan-ng/toolchain
        sh dl_toolchain.sh

    - name: Compile new toolchain
      if: env.USE_PRECOMPILED_TOOLCHAIN == 'false' && !cancelled()
      run: |
        cd opt/padavan-ng/toolchain
        ./build_toolchain.sh

    - name: Clean up files
      run: |
        cd opt/padavan-ng/trunk
        ./clear_tree.sh

    - name: Compile firmware
      run: |
        cd opt/padavan-ng/trunk
        fakeroot ./build_firmware.sh
        echo "::set-env name=DATE::$(date +"%Y%m%d%H%M")"

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      with:
        name: ${{ env.DEVICE_NAME }}_padavan_firmware_${{ env.DATE }}
        path: opt/padavan-ng/trunk/images/
